%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/snavrag/MyWork/MyProjects_HDrive/HRX_Walking_HDrive/Statistics_folder/H_Data_Raw.xlsx
%    Worksheet: GaitData_Right
%
% Auto-generated by MATLAB on 15-Aug-2022 17:14:14

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 13);

% Specify column names and types
opts.VariableNames = ["Participant", "Condition", "dls", "StrideTime", "Stance Phase", "Step length", "Step Width", "Stride Length", "Swing Phase", "MoS_Medial","MoS_AP","Locations"];
opts.VariableTypes = ["categorical", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify sheet and range
opts.Sheet = "GaitData_Right";
opts.DataRange = "A2:L27565";

% Specify variable properties
opts = setvaropts(opts, ["Participant", "Condition", "Locations"], "EmptyFieldRule", "auto");

% Import the data
GaitData = readtable("C:\Users\ykuk0\Desktop\HRX\Stats\HMdata_Final_yk.xlsx", Sheet="GaitData_Right", VariableNamingRule='preserve');

%% Clear temporary variables
clear opts

%% Bin it mate!

yy = table2array(GaitData(:,12));  % taking the second column
zz = GaitData;  % according to the diagram

     % binning
     edges = 0:15000:180000;
     [N, ~, gbin] = histcounts(yy,edges);


     % match the values of zz to the bins that elements
     % of yy went into.

%% Work on the bins mate!

[g, gid] = findgroups(gbin);
Tc = splitapply(@(varargin) varargin, GaitData, g);
% Allocate empty cell array fo sizxe equal to number of rows in T_Split
subTables = cell(size(Tc, 1), 1);
% Create sub tables for participants and conditions
for i = 1:size(Tc, 1)
    subTables{i} = table(Tc{i, :}, 'VariableNames', ...
                        GaitData.Properties.VariableNames);
    subgroupTables{i} = table(subTables{i}.Participant, subTables{i}.Condition, ...
                        'VariableNames', GaitData.Properties.VariableNames(1:2));
    suboutcomesTables{i} = subTables{i}(:,3:end-1);
    [gPC{i}, gPCidI{i}] = findgroups(subgroupTables{i});
    for outcomes = 1:size(suboutcomesTables{i}, 2)
        mean_gPC{i}(:,outcomes) = splitapply(@mean, suboutcomesTables{i}(:,outcomes), gPC{i});
        std_gPC{i}(:,outcomes) = splitapply(@std, suboutcomesTables{i}(:,outcomes), gPC{i});
    end
end


% Create sub tables for conditions
subTables_cond = cell(size(Tc, 1), 1);

for j = 1:size(Tc, 1)
    subTables_cond{j} = table(Tc{j, :}, 'VariableNames', ...
                        GaitData.Properties.VariableNames);
    subgroupTables_cond{j} = table(subTables{j}.Condition, ...
                        'VariableNames', GaitData.Properties.VariableNames(2));
    suboutcomesTables_cond{j} = subTables_cond{j}(:,3:end-1);
    [gPC_cond{j}, gPCidI_cond{j}] = findgroups(subgroupTables_cond{j});
    for outcomes_c = 1:size(suboutcomesTables_cond{j}, 2)
        mean_gPC_cond{j}(:,outcomes_c) = splitapply(@mean, suboutcomesTables_cond{j}(:,outcomes_c), gPC_cond{j});
        std_gPC_cond{j}(:,outcomes_c) = splitapply(@std, suboutcomesTables_cond{j}(:,outcomes_c), gPC_cond{j});
    end
end
legend_no = [];
for outtoPlot = 2%:7
    for section = 1:size(unique(g),1)

        plot(std_gPC_cond{1,section}(:,outtoPlot))
        hold on
        legend_no = [legend_no; section];
    end
%     hold off;
%     figure on;
end
legend(num2str(legend_no));
