% % function [ emgData, copData, fData, sf, triggerData] = loaddata( filename, data_1 )
% function [ emgData, sf, triggerData] = loaddata( filename, data_1 )
% % loads emgData form Voltage_annel 1-8, triggerData and sampling frequency from the mat. file.
% sf = data_1.EMG.(genvarname(filename(9:12))).sf;
% triggerData = data_1.EMG.(genvarname(filename(9:12))).trigger;
%
% emgData = [data_1.EMG.(genvarname(filename(9:12))).Voltage_1 data_1.EMG.(genvarname(filename(9:12))).Voltage_2 ...
%     data_1.EMG.(genvarname(filename(9:12))).Voltage_3 ...
%     data_1.EMG.(genvarname(filename(9:12))).Voltage_4 ...
%     data_1.EMG.(genvarname(filename(9:12))).Voltage_5 ...
%     data_1.EMG.(genvarname(filename(9:12))).Voltage_6 ...
%     data_1.EMG.(genvarname(filename(9:12))).Voltage_7 ...
%     data_1.EMG.(genvarname(filename(9:12))).Voltage_8];
%
% end
%
% function [ emgData, copData, fData, sf, triggerData] = loaddata( filename, data_1 )
function [ emgData, sf, triggerData] = loaddata( data_1 )
% loads emgData form Voltage_annel 1-8, triggerData and sampling frequency from the mat. file.
sf = data_1.EMG.sf;
triggerData = data_1.EMG.Electric_Current_Trigger_Output;

emgData = [data_1.EMG.Voltage_1 data_1.EMG.Voltage_2 ...
    data_1.EMG.Voltage_3 ...
    data_1.EMG.Voltage_4 ...
    data_1.EMG.Voltage_5 ...
    data_1.EMG.Voltage_6 ...
    data_1.EMG.Voltage_7 ...
    data_1.EMG.Voltage_8...
    data_1.EMG.Voltage_9...
    data_1.EMG.Voltage_10...
    data_1.EMG.Voltage_11...
    data_1.EMG.Voltage_12...
    data_1.EMG.Voltage_13...
    data_1.EMG.Voltage_14];

end
